### ISSUE TITLE
Example using Search

### ISSUE THREAD

**Issue by aranasaurus** [danthorpe/TaylorSource#47]
Hey Dan,
A co-worker and I were trying to add support for Full Text Search, and we got the YapDatabase side of things set up correctly, but we're having a hard time figuring out how to plug it in to TaylorSource. It'd be really nice to see an example implementation of Search with YapDB and TaylorSource.

Thanks again for all your work on these libraries!

**Comment by danthorpe** [comment]
Hey @aranasaurus - sure no problem, will create a gist for you and link to it here...

Also - I'm giving Taylor Source a bit of an overhaul at the moment - mostly updating it to be more Swift 2.0 style of APIs (with `ErrorType`s etc). So, feedback around all the rough edges would be great - feel free to add comments to Issue #44. :)

**Comment by aranasaurus** [comment]
nice! Will do! We've been using it fairly extensively over the past few weeks, I'll have to go over all my stuff and compile a list of notes for you :)

**Comment by danthorpe** [comment]
@aranasaurus hi - take a look at: https://github.com/danthorpe/Examples/pull/4

This took me about 2 hours to write from scratch, although I copied the initial domain from the US Cities example in this repo.

See the comment in that PR - I've tried to explain it all. Really hope this helps!

**Comment by aranasaurus** [comment]
Wow, thanks a lot! I'll be taking a look at this tomorrow morning, and I'll send it to my co-worker too!

**Comment by danthorpe** [comment]
Gonna close this. Example is in my examples repo.
